services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_ts_ecom_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/ecomdb
    env_file:
      - .env
    depends_on:
      - mongo

  # MongoDB Service
  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
